project:
  type: website
  output-dir: docs

website:
  title: "Isai Garcia-Baza"
  navbar:
    left:
      - href: index.qmd
      - resume.qmd
  cookie-consent: true
  google-analytics: G-0CE131HDEB

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    email-obfuscation: javascript



