project:
  type: website
  output-dir: docs

website:
  title: "Isai Garcia-Baza"
  navbar:
    left:
      - href: index.qmd
      - research.qmd
      - skills.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



